services:
  ipfs-node:
    image: ipfs/kubo:latest
    restart: unless-stopped
    volumes:
      - ipfs-data:/data/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - ipfs_node
    environment:
      - name=value
    restart: unless-stopped
volumes:
  ipfs-data: