services:
  ipfs-node:
    image: ipfs/kubo:latest
    restart: unless-stopped
    volumes:
      - ipfs-data:/data/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"

volumes:
  ipfs-data: