services:
  ipfs-node:
    image: ipfs/kubo:latest
    restart: unless-stopped
    volumes:
      - ipfs-data:/data/ipfs
      - ./kubo/001-config.sh:/container-init.d/001-config.sh
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - ipfs-node
    environment:
      - name=value
    restart: unless-stopped
volumes:
  ipfs-data:
